# Generated by Django 4.1.6 on 2023-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malllist',
            name='list_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
